version: "3"
services:
  templebase:
    image: localhost:5000/templebase:latest
    network_mode: "host"
    ports:
      - "8060:8060"

  nginx:
    image: nginx:latest
    links:
      - templebase
    ports:
      - "8090:8090"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    extra_hosts:
      - "somehost:172.19.0.1"


